#!/usr/bin/env bash
## Volumes to sync
ORIG_VOLUME='frø'
DEST_VOLUMES[0]='.'
DEST_VOLUMES[1]='Macintosh HD'

## Assets to sync (per Destination Volume)
FILES_0=()
FOLDERS_0=(
'music'
'photo_bank'
'flickr_backup'
'flickr_backup_desktop'
'podcasts'
'Wintermute_backup'
)

FILES_1=(
'README.md'
)
FOLDERS_1=(
'music'
'test'
)

FILES_ALL=(FILES_0 FILES_1)
FOLDERS_ALL=(FOLDERS_0 FOLDERS_1)

## Common code
# flags
REVERSE=0
NOOP=0

usage () {
  printf "Usage: $(basename $0) [-n] [-r]
          -n : no operation (just check)
          -r : reverse (current volume becomes the destination)
"
}

while getopts ":rn" arg; do
  case $arg in
  r)
    REVERSE=1
  ;;
  n)
    NOOP=1
  ;;
  *) 
    usage
    exit 127
  ;;
  esac
done
shift $(($OPTIND -1))

# Select destination volume
SELECTED_DEST_VOLUME=$([ $# -ge 1 ] && printf $1 || printf 0)
DEST_VOLUME=${DEST_VOLUMES[$SELECTED_DEST_VOLUME]}

# Check destination volume
if [ -z "${DEST_VOLUME}" ]; then
  echo "PLEASE USE ONE OF THE FOLLOWING IDs (or NO ID for [0])"
  for i in $(seq 0 1 $((${#DEST_VOLUMES[@]} -1)) ); do
   echo "- ${i} for ${DEST_VOLUMES[i]}"
  done
  exit 1
fi
if [ ! -d "/Volumes/${DEST_VOLUME}" ]; then
  echo "VOLUME '${DEST_VOLUME}' is not mounted. PLEASE DO SO."
  exit 2
fi


## Start process
echo "USING volume '${DEST_VOLUME}'"

# Select specific set of assets
declare -n FILES="${FILES_ALL[${SELECTED_DEST_VOLUME}]}"
declare -n FOLDERS="${FOLDERS_ALL[${SELECTED_DEST_VOLUME}]}"

# TODO: remove this debugging
printf "\nfiles ---\n"
printf '%s\n' ${FILES[@]}
printf "\nfolders ---\n"
printf '%s\n' ${FOLDERS[@]}


ACTION=$([ $NOOP -eq 1 ] && printf "CHECKING" || printf "UPDATING")
printf "${ACTION} backup from '${ORIG_VOLUME}' to '${DEST_VOLUME}'\n"
# TODO : REMOVE THE ECHO SO THAT OPERATIONS REALLY TAKE PLACE
for i in $(seq 0 1 $((${#FILES[@]} -1)) 2>/dev/null); do
  printf "> ${FILES[i]}\n"
  echo rsync -aiun ./${FILES[i]} /Volumes/${DEST_VOLUME} --delete --exclude-from=./rsync_exclude
done

for i in $(seq 0 1 $((${#FOLDERS[@]} -1)) 2>/dev/null); do
  printf "> ${FOLDERS[i]}\n"
  echo rsync -aiun ./${FOLDERS[i]}/ /Volumes/${DEST_VOLUME}/${FOLDERS[i]}/ --delete --exclude-from=./rsync_exclude
done


